require:
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'tmp/**/*'

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
