AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'tmp/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
